MMDefStart;
  class ZoomPieChart;
  attr ZoomPieChart.nameAttribute:string;
  attr ZoomPieChart.valueAttribute:string;
  attr ZoomPieChart.filtersToAttributes:string;  // filterId:attrName;filterId:attrName
  rel ZoomPieChart.subClassOf.Planet;
MMDefEnd;
