MMDefStart;
  class LaunchTransformationCommand;
    rel LaunchTransformationCommand.subClassOf.Command;
    attr LaunchTransformationCommand.uri:string;
  class GalaxyEngine;
    attr GalaxyEngine.onRunEvent:string;
    attr GalaxyEngine.useGalacticIcons:boolean;
  class DataGalaxy;
    attr DataGalaxy.layoutInfo:string;
  class GalaxyComponent;
    attr GalaxyComponent.id:string;
    attr GalaxyComponent.name:string;
    attr GalaxyComponent.state:string;
    attr GalaxyComponent.stateMessage:string;
    attr GalaxyComponent.location:string;
  class RunConfiguration;
    attr RunConfiguration.name:string;
    attr RunConfiguration.description:string;
  class Star;
    attr Star.emptyOnInit:boolean;
    attr Star.starDataType:string;
  class Planet;
  class StellarWind;
    attr StellarWind.description:string;
  class CrossFilter;
  class StarData;
  class ConfigurePlanet;
    attr ConfigurePlanet.frameLocation:string;
  class VisualizePlanet;
    attr VisualizePlanet.frameLocation:string;
  class ConfigureStar;
    attr ConfigureStar.frameLocation:string;
  class InitializeStar;
  class ConfigureCrossFilter;
    attr ConfigureCrossFilter.frameLocation:string;
  class ConfigureStellarWind;
    attr ConfigureStellarWind.frameLocation:string;
  class EmitStellarWind;
  class EditGalaxyCommand;
  class Frame;
  class RefreshGalaxyCommand;
  class FinalizeStar;
  class CleanupStar;
    rel Star.subClassOf.GalaxyComponent;
    rel Planet.subClassOf.GalaxyComponent;
    rel StellarWind.subClassOf.GalaxyComponent;
    rel CrossFilter.subClassOf.GalaxyComponent;
    rel ConfigurePlanet.subClassOf.LaunchTransformationCommand;
    rel VisualizePlanet.subClassOf.LaunchTransformationCommand;
    rel ConfigureStar.subClassOf.LaunchTransformationCommand;
    rel InitializeStar.subClassOf.LaunchTransformationCommand;
    rel ConfigureCrossFilter.subClassOf.LaunchTransformationCommand;
    rel ConfigureStellarWind.subClassOf.LaunchTransformationCommand;
    rel EmitStellarWind.subClassOf.LaunchTransformationCommand;
    rel EditGalaxyCommand.subClassOf.Command;
    rel RefreshGalaxyCommand.subClassOf.Command;
    rel FinalizeStar.subClassOf.LaunchTransformationCommand;
    rel CleanupStar.subClassOf.LaunchTransformationCommand;
  compos DataGalaxy.[*]dataGalaxy/galaxyComponent[*].GalaxyComponent;
  assoc RunConfiguration.[*]rc1/visibleComponent[*].GalaxyComponent;
  assoc RunConfiguration.[*]rc2/mustConfigureComponent[*].GalaxyComponent;
  assoc RunConfiguration.[*]rc3/deactivatedComponent[*].GalaxyComponent;
  compos GalaxyEngine.[*]galaxyEngine/dataGalaxy[1].DataGalaxy;
  assoc Planet.[*]planet/star[1].Star;
  assoc StellarWind.[*]consumer/source[*].Star;
  assoc StellarWind.[1..*]producer/target[1].Star;
  assoc Planet.[*]planet/crossFilter[*].CrossFilter;
  assoc StellarWind.[*]stellarWind/crossFilter[*].CrossFilter;
  compos Star.[*]star/starData[0..1].StarData;
  assoc ConfigurePlanet.[*]configurePlanet/planet[1].Planet;
  assoc VisualizePlanet.[*]visualizePlanet/planet[1].Planet;
  assoc ConfigureStar.[*]configureStar/star[1].Star;
  assoc InitializeStar.[*]initializeStar/star[1].Star;
  assoc ConfigureCrossFilter.[*]configureCrossFilter/crossFilter[1].CrossFilter;
  assoc ConfigureStellarWind.[*]configureStellarWind/stellarWind[1].StellarWind;
  assoc EmitStellarWind.[*]emitStellarWind/stellarWind[1].StellarWind;
  assoc DataGalaxy.[*]dataGalaxy/frame[1].Frame;
  assoc EditGalaxyCommand.[*]editGalaxyCommand/dataGalaxy[1].DataGalaxy;
  compos DataGalaxy.[*]dataGalaxy/runConfiguration[*].RunConfiguration;
  assoc DataGalaxy.[*]dg1/activeRunConfiguration[0..1].RunConfiguration;
  assoc RefreshGalaxyCommand.[*]refreshGalaxyCommand/modifiedComponent[*].GalaxyComponent;
  assoc FinalizeStar.[*]finalizeStar/star[1].Star;
  assoc RefreshGalaxyCommand.[*]refreshGalaxyCommand/dataGalaxy[1].DataGalaxy;
  assoc GalaxyComponent.[*]galaxyComponent/frame[0..1].Frame;
  assoc CleanupStar.[*]cleanupStar/star[1].Star;
MMDefEnd;
