MMDefStart;
  class "JSON array to tree";
  attr "JSON array to tree".idAttributeName:string;
  attr "JSON array to tree".childrenAttributeName:string;
  attr "JSON array to tree".isParentOf:string;
  rel "JSON array to tree".subClassOf.StellarWind;
MMDefEnd;
